version: '3.8'

services:
  assistant-epargne:
    build: .
    container_name: assistant-epargne-intelligent
    ports:
      - "8501:8501"
    volumes:
      # Monter un volume pour persister les données générées
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    restart: unless-stopped
    networks:
      - assistant-network

networks:
  assistant-network:
    driver: bridge 